
N = int(input('Digite um valor: '))
print(N)
if N >= 100:
    notaCem = int(N / 100)
    print('%i nota(s) de R$ 100,00' % notaCem)
    N = N - notaCem * 100
    nota_cinquenta = int(N / 50)
    print('%i nota(s) de R$ 50,00' % nota_cinquenta)
    N -= (nota_cinquenta * 50)
    nota_vinte = int(N / 20)
    print('%i nota(s) de R$ 20,00' % nota_vinte)
    N -= (nota_vinte * 20)
    nota_dez = int(N / 10)
    print('%i nota(s) de R$ 10,00' % nota_dez)
    N -= (nota_dez * 10)
    nota_cinco = int(N / 5)
    print('%i nota(s) de R$ 5,00' % nota_cinco)
    N -= (nota_cinco * 5)
    nota_dois = int(N / 2)
    print('%i nota(s) de R$ 2,00' % nota_dois)
    N -= (nota_dois * 2)
    print('%i nota(s) de R$ 1,00' % N)
elif N >= 50:
    nota_cinquenta = int(N / 50)
    print('%i nota(s) de R$ 50,00' % nota_cinquenta)
    N -= (nota_cinquenta * 50)
    nota_vinte = int(N / 20)
    print('%i nota(s) de R$ 20,00' % nota_vinte)
    N -= (nota_vinte * 20)
    nota_dez = int(N / 10)
    print('%i nota(s) de R$ 10,00' % nota_dez)
    N -= (nota_dez * 10)
    nota_cinco = int(N / 5)
    print('%i nota(s) de R$ 5,00' % nota_cinco)
    N -= (nota_cinco * 5)
    nota_dois = int(N / 2)
    print('%i nota(s) de R$ 2,00' % nota_dois)
    N -= (nota_dois * 2)
    print('%i nota(s) de R$ 1,00' % N)
elif N >= 20:
    nota_vinte = int(N / 20)
    print('%i nota(s) de R$ 20,00' % nota_vinte)
    N -= (nota_vinte * 20)
    nota_dez = int(N / 10)
    print('%i nota(s) de R$ 10,00' % nota_dez)
    N -= (nota_dez * 10)
    nota_cinco = int(N / 5)
    print('%i nota(s) de R$ 5,00' % nota_cinco)
    N -= (nota_cinco * 5)
    nota_dois = int(N / 2)
    print('%i nota(s) de R$ 2,00' % nota_dois)
    N -= (nota_dois * 2)
    print('%i nota(s) de R$ 1,00' % N)
elif N >= 10:
    nota_dez = int(N / 10)
    print('%i nota(s) de R$ 10,00' % nota_dez)
    N -= (nota_dez * 10)
    nota_cinco = int(N / 5)
    print('%i nota(s) de R$ 5,00' % nota_cinco)
    N -= (nota_cinco * 5)
    nota_dois = int(N / 2)
    print('%i nota(s) de R$ 2,00' % nota_dois)
    N -= (nota_dois * 2)
    print('%i nota(s) de R$ 1,00' % N)
elif N >= 5:
    nota_cinco = int(N / 5)
    print('%i nota(s) de R$ 5,00' % nota_cinco)
    N -= (nota_cinco * 5)
    nota_dois = int(N / 2)
    print('%i nota(s) de R$ 2,00' % nota_dois)
    N -= (nota_dois * 2)
    print('%i nota(s) de R$ 1,00' % N)
elif N >= 2:
    nota_dois = int(N / 2)
    print('%i nota(s) de R$ 2,00' % nota_dois)
    N -= (nota_dois * 2)
    print('%i nota(s) de R$ 1,00' % N)
elif N >= 1:
    print('%i nota(s) de R$ 1,00' % N)
